### PR TITLE
Reduce memory consumption for Kubernetes source configuration

### LINKED ISSUE #1403: Increased resources consumption configuring some sources
## Before you submit the issue

- [x] Search open and closed issues for duplicates.
- [x] Read the contributing guidelines (CONTRIBUTING.md file on root of the repository).
- [x] Ask in Slack channel `helping-hands`.

## Description

We use Botkube mainly to receive alerts based on specific events.

Migrating from 0.18.0 to 1.8.0, we translated the configuration from old (0.18) to new (1.8) syntax, but we face some issues:
- we see error logs same as described in the Slack thread https://botkube.slack.com/archives/C01CR1KS55K/p1708685516373879.
- Botkube keeps restarts because of livenessProbe failing (sometimes because of OOMKilled during startup, but this doesn’t occur that often), but we increased resources like: requests 1000m/1Gi, limits 3000m/3Gi. We set those values based on Grafana spikes we observed. To be honest they look really high, especially if compared to version 0.18! Actually it seems that the adoption of the plugin model increased exponentially the resources usage :disappointed:

Please note that the above mentioned issues happen also with the default global_config coming out of the helm-chart with following sources enabled: k8s-all-events, k8s-create-events, k8s-err-events, k8s-err-with-logs-events, k8s-recommendation-events

## Expected behavior

Even with many configured sources, Botkube should consume up to 1000m cpu and 1Gi mem, like in older versions <= 1.0.0

## Actual behavior

With many configured sources, Botkube consumes up to 3000m cpu and 3Gi mem.

## Steps to reproduce

Just deploy Botkube using following configuration:

<details>
  <summary>expand</summary>

global_config.yaml

```yaml
executors:
  bins-management:
    botkube/exec:
      config:
        templates:
        - ref: github.com/kubeshop/botkube//cmd/executor/exec/templates?ref=v1.8.0
      context:
        rbac:
          group:
            prefix: ""
            static:
              values:
              - botkube-plugins-default
            type: Static
      displayName: Exec
      enabled: false
  k8s-default-tools:
    botkube/helm:
      config:
        defaultNamespace: default
        helmCacheDir: /tmp/helm/.cache
        helmConfigDir: /tmp/helm/
        helmDriver: secret
      context:
        rbac:
          group:
            prefix: ""
            static:
              values:
              - botkube-plugins-default
            type: Static
      displayName: Helm
      enabled: false
    botkube/kubectl:
      config:
        defaultNamespace: default
      context:
        rbac:
          group:
            prefix: ""
            static:
              values:
              - botkube-plugins-default
            type: Static
      displayName: Kubectl
      enabled: true

aliases:
  k:
    command: kubectl
    displayName: Kubectl alias
  kc:
    command: kubectl
    displayName: Kubectl alias
  x:
    command: exec
    displayName: Exec alias

actions:
  describe-created-resource:
    bindings:
      executors:
      - k8s-default-tools
      sources:
      - k8s-create-events
    command: kubectl describe {{ .Event.Kind | lower }}{{ if .Event.Namespace }} -n
      {{ .Event.Namespace }}{{ end }} {{ .Event.Name }}
    displayName: Describe created resource
    enabled: false
  show-logs-on-error:
    bindings:
      executors:
      - k8s-default-tools
      sources:
      - k8s-err-with-logs-events
    command: kubectl logs {{ .Event.Kind | lower }}/{{ .Event.Name }} -n {{ .Event.Namespace
      }}
    displayName: Show logs on error
    enabled: false

settings:
  clusterName: ceiba-cicd
  healthPort: 2114
  lifecycleServer:
    enabled: true
    port: 2113
  log:
    disableColors: false
    formatter: json
    level: info
  persistentConfig:
    runtime:
      configMap:
        annotations: {}
        name: botkube-runtime-config
      fileName: _runtime_state.yaml
    startup:
      configMap:
        annotations: {}
        name: botkube-startup-config
      fileName: _startup_state.yaml
  systemConfigMap:
    name: botkube-system
  upgradeNotifier: true

sources:
  argo:
    displayName: "Argo"
    botkube/kubernetes:
      enabled: true
      config:
        event:
          types:
          - create
          - update
          - delete
          - error
        namespaces:
          include:
            - argo
            - argo-events
            - argocd
        resources:
        # CRDs
        ## argocd
        - type: argoproj.io/v1alpha1/applications
          event:
            types:
            - error
          updateSetting:
            includeDiff: true
        - type: argoproj.io/v1alpha1/appprojects
          updateSetting:
            includeDiff: true
            fields:
              - spec
        ## argo-events
        - type: argoproj.io/v1alpha1/eventbus
          updateSetting:
            includeDiff: true
            fields:
              - spec.nats
        - type: argoproj.io/v1alpha1/eventsources
          updateSetting:
            includeDiff: true
            fields:
              - spec
        - type: argoproj.io/v1alpha1/sensors
          updateSetting:
            includeDiff: true
            fields:
              - spec
        ## argo-workflows
        - type: argoproj.io/v1alpha1/clusterworkflowtemplates
          updateSetting:
            includeDiff: true
            fields:
              - spec
        - type: argoproj.io/v1alpha1/workfloweventbindings
          updateSetting:
            includeDiff: true
            fields:
              - spec
        - type: argoproj.io/v1alpha1/workflows
          event: # INFO: created by ArgoEvents Sensors for each pipeline
            types:
            - error
          updateSetting:
            includeDiff: true
            fields:
              - spec
        - type: argoproj.io/v1alpha1/workflowtasksets
          updateSetting:
            includeDiff: true
            fields:
              - spec
        - type: argoproj.io/v1alpha1/workflowtemplates
          updateSetting:
            includeDiff: true
            fields:
              - spec
      context:
        rbac:
          group:
            prefix: ""
            static:
              values:
              - botkube-plugins-default
            type: Static
  infra:
    displayName: "Infra"
    botkube/kubernetes:
      enabled: true
      config:
        event:
          types:            
          - create
          - update
          - delete
          - error
        namespaces:
          include:
            - argo
            - argo-events
            - argocd
            - auditing
            - cicd-pipelines
            - default
            - ingress
            - kube-node-lease
            - kube-public
            - reloader
            - support
        resources:
          # K8s
          - type: v1/configmaps
            namespaces:
              exclude:
                # WARN: too many notifications because of new features
                - cicd-pipelines
                - cicd-pipelines-ast
                - cicd-pipelines-commons
                - cicd-pipelines-devops
                - cicd-pipelines-die
                - cicd-pipelines-investigations
                - cicd-pipelines-ip
                - cicd-pipelines-research
                - cicd-pipelines-sp
                - cicd-pipelines-tc
                - cicd-pipelines-tee
                - cicd-pipelines-ts
            updateSetting:
              includeDiff: true
              fields:
                - data
          - type: v1/pods
            namespaces:
              exclude:
                # WARN: too many notifications because of pipelines running
                - cicd-pipelines
                - cicd-pipelines-ast
                - cicd-pipelines-commons
                - cicd-pipelines-devops
                - cicd-pipelines-die
                - cicd-pipelines-investigations
                - cicd-pipelines-ip
                - cicd-pipelines-research
                - cicd-pipelines-sp
                - cicd-pipelines-tc
                - cicd-pipelines-tee
                - cicd-pipelines-ts
            updateSetting:
              includeDiff: true
              fields:
                - spec.serviceAccountName
                - spec.securityContext
                - spec.containers[*].image
                - spec.containers[*].resources
                - spec.containers[*].securityContext
          - type: apps/v1/daemonsets
            updateSetting:
              includeDiff: true
              fields:
                - spec.template.spec
                # WARN: not always defined
                # - spec.template.spec.serviceAccountName
                # - spec.template.spec.securityContext
                # - spec.template.spec.containers[*].image
                # - spec.template.spec.containers[*].resources
                # - spec.template.spec.containers[*].securityContext
          - type: apps/v1/deployments
            updateSetting:
              includeDiff: true
              fields:
                - spec.replicas
                - spec.template.spec
                # WARN: not always defined
                # - spec.template.spec.serviceAccountName
                # - spec.template.spec.securityContext
                # - spec.template.spec.containers[*].image
                # - spec.template.spec.containers[*].resources
                # - spec.template.spec.containers[*].securityContext
          - type: apps/v1/statefulsets
            updateSetting:
              includeDiff: true
              fields:
                - spec.replicas
                - spec.template.spec
                # WARN: not always defined
                # - spec.template.spec.serviceAccountName
                # - spec.template.spec.securityContext
                # - spec.template.spec.containers[*].image
                # - spec.template.spec.containers[*].resources
                # - spec.template.spec.containers[*].securityContext
          - type: batch/v1/cronjobs
            updateSetting:
              includeDiff: true
              fields:
                - spec.suspend
                - spec.schedule
                - spec.jobTemplate.spec.template   # INFO: better stay more general
                # WARN: not always defined
                # - spec.jobTemplate.spec.template.serviceAccountName
                # - spec.jobTemplate.spec.template.securityContext
                # - spec.jobTemplate.spec.template.containers[*].image
                # - spec.jobTemplate.spec.template.containers[*].resources
                # - spec.jobTemplate.spec.template.containers[*].securityContext
          - type: batch/v1/jobs
            updateSetting:
              includeDiff: true
              fields:
                - status
                - status.startTime
                - status.completionTime
                - status.succeeded
                - status.conditions[*].status
          #       - status.conditions[*].type   # WARN: provided in examples but causing error "while finding value from jsonpath: \"status.conditions[*].type\" [..] conditions is not found"
          - type: v1/persistentvolumeclaims
            namespaces:
              exclude:
                # WARN: too many notifications because of pipelines running
                - cicd-pipelines
                - cicd-pipelines-ast
                - cicd-pipelines-commons
                - cicd-pipelines-devops
                - cicd-pipelines-die
                - cicd-pipelines-investigations
                - cicd-pipelines-ip
                - cicd-pipelines-research
                - cicd-pipelines-sp
                - cicd-pipelines-tc
                - cicd-pipelines-tee
                - cicd-pipelines-ts
            updateSetting:
              includeDiff: true
              fields:
                - spec.accessModes
                - spec.resources.requests.storage
          - type: v1/persistentvolumes
            updateSetting:
              includeDiff: true
      context:
        rbac:
          group:
            prefix: ""
            static:
              values:
              - botkube-plugins-default
            type: Static
  infra-monitoring:   # INFO: too many `pods` create and delete due to `cronjobs`
    displayName: "Monitoring infra"
    botkube/kubernetes:
      enabled: true
      config:          
        event:
          types:
          - create
          - update
          - delete
          - error
        namespaces:
          include:
            - monitoring
        resources:
          # K8s
          - type: v1/configmaps
            updateSetting:
              includeDiff: true
              fields:
                - data
          # - type: v1/secrets
          #   updateSetting:
          #     includeDiff: true
          #     fields:
          #       - data
          - type: v1/pods
            event:   # WARN: too many `update` notifications
              types:
              - update
              - error
            updateSetting:
              includeDiff: true
              fields:
                - spec.serviceAccountName
                - spec.securityContext
                - spec.containers[*].image
                - spec.containers[*].resources
                - spec.containers[*].securityContext
          - type: apps/v1/daemonsets
            updateSetting:
              includeDiff: true
              fields:
                - spec.template.spec
          - type: apps/v1/deployments
            updateSetting:
              includeDiff: true
              fields:
                - spec.replicas
                - spec.template.spec
          - type: apps/v1/statefulsets
            updateSetting:
              includeDiff: true
              fields:
                - spec.replicas
                - spec.template.spec
          - type: batch/v1/cronjobs
            updateSetting:
              includeDiff: true
              fields:
                - spec.suspend
                - spec.schedule
                - spec.jobTemplate.spec.template
          - type: v1/persistentvolumeclaims
            updateSetting:
              includeDiff: true
              fields:
                - spec.accessModes
                - spec.resources.requests.storage
          - type: v1/persistentvolumes
            updateSetting:
              includeDiff: true
      context:
        rbac:
          group:
            prefix: ""
            static:
              values:
              - botkube-plugins-default
            type: Static
  infra-logging:   # INFO: too many `configmaps` updates
    displayName: "Logging infra"
    botkube/kubernetes:
      enabled: true
      config:
        event:
          types:
          - create
          - update
          - delete
          - error
        namespaces:
          include:
            - logging
        resources:
          # K8s
          - type: v1/configmaps
            event:   # WARN: too many `update` notifications
              types:
              - create
              - delete
              - error
            updateSetting:
              includeDiff: true
              # fields:   # WARN: missing field `data` for `logging-operator.logging.banzaicloud.io`
              #   - data
          - type: v1/pods
            updateSetting:
              includeDiff: true
              fields:
                - spec.serviceAccountName
                - spec.securityContext
                - spec.containers[*].image
                - spec.containers[*].resources
                - spec.containers[*].securityContext
          - type: apps/v1/daemonsets
            updateSetting:
              includeDiff: true
              fields:
                - spec.template.spec
          - type: apps/v1/deployments
            updateSetting:
              includeDiff: true
              fields:
                - spec.replicas
                - spec.template.spec
          - type: apps/v1/statefulsets
            updateSetting:
              includeDiff: true
              fields:
                - spec.replicas
                - spec.template.spec
          - type: batch/v1/cronjobs
            updateSetting:
              includeDiff: true
              fields:
                - spec.suspend
                - spec.schedule
                - spec.jobTemplate.spec.template
          - type: v1/persistentvolumeclaims
            updateSetting:
              includeDiff: true
              fields:
                - spec.accessModes
                - spec.resources.requests.storage
          - type: v1/persistentvolumes
            updateSetting:
              includeDiff: true
      # WARN: too many errors like
      #   - failed to garbage collect required amount of images
      #   - {"unmanaged": {"net.core.bpf_jit_harden": "0", "net.netfilter.nf_conntrack_buckets": "131072"}}
      #   - Memory cgroup out of memory: Killed process
      # nodes:
      #   displayName: "Nodes"
      #   botkube/kubernetes:
      #     events:
      #       - all
      #     namespaces:
      #       include:
      #         - ".*"
      #     resources:
      #       # K8s
      #       - name: v1/nodes
      #         updateSetting:
      #           includeDiff: true
      context:
        rbac:
          group:
            prefix: ""
            static:
              values:
              - botkube-plugins-default
            type: Static
  namespaces:
    displayName: "Namespaces"
    botkube/kubernetes:
      enabled: true
      config:
        event:
          types:
          - create
          - update
          - delete
          - error
        namespaces:
          include:
            - ".*"
        resources:
        # K8s
        - type: v1/namespaces
          updateSetting:
            includeDiff: true
      context:
        rbac:
          group:
            prefix: ""
            static:
              values:
              - botkube-plugins-default
            type: Static
  security:
    displayName: "Security"
    botkube/kubernetes:
      enabled: true
      config:
        event:
          types:
          - create
          - update
          - delete
          - error
        namespaces:
          include:
            - ".*"
          exclude:   # WARN: take precedence over `include`
            - kube-system
        resources:
          # K8s
          - type: v1/serviceaccounts
            events:   # WARN: too many `update` notifications
              - create
              - delete
              - error
            updateSetting:
              includeDiff: true
          - type: rbac.authorization.k8s.io/v1/clusterrolebindings
            updateSetting:
              includeDiff: true
              fields:
                - roleRef
                - subjects[*]
                # WARN: not always defined
                # - subjects[*].name
                # - subjects[*].namespace
          - type: rbac.authorization.k8s.io/v1/clusterroles
            updateSetting:
              includeDiff: true
              fields:
                - rules
          - type: rbac.authorization.k8s.io/v1/rolebindings
            updateSetting:
              includeDiff: true
              fields:
                - roleRef
                - subjects[*]
                # WARN: not always defined
                # - subjects[*].name
                # - subjects[*].namespace
          - type: rbac.authorization.k8s.io/v1/roles
            updateSetting:
              includeDiff: true
              fields:
                - rules
          - type: admissionregistration.k8s.io/v1/mutatingwebhookconfigurations
            updateSetting:
              includeDiff: true
          - type: admissionregistration.k8s.io/v1/validatingwebhookconfigurations
            updateSetting:
              includeDiff: true
          - type: networking.k8s.io/v1/ingresses
            updateSetting:
              includeDiff: true
              fields:
                - spec.rules   # array
          - type: networking.k8s.io/v1/networkpolicies
            updateSetting:
              includeDiff: true
              fields:
                - spec.podSelector
                - spec.policyTypes   # array
                # WARN: not always defined
                # - spec.egress   # array
                # - spec.ingress   # array
          # CRDs
          ## gcp/gke
          - type: cloud.google.com/v1/backendconfigs
            updateSetting:
              includeDiff: true
              fields:
                - spec
                # WARN: not always defined
                # - spec.healthCheck
                # - spec.iap
          - type: cloud.google.com/v1beta1/backendconfigs
            updateSetting:
              includeDiff: true
              fields:
                - spec
                # WARN: not always defined
                # - spec.healthCheck
                # - spec.iap
          # - type: networking.gke.io/v1/frontendconfigs
          #   updateSetting:
          #     includeDiff: true
          #     fields:
          #       - spec.redirectToHttps
          - type: networking.gke.io/v1beta1/frontendconfigs   # DEPRECATED
            updateSetting:
              includeDiff: true
              fields:
                - spec.redirectToHttps
          - type: networking.gke.io/v1/managedcertificates
            updateSetting:
              includeDiff: true
              fields:
                - spec.domains   # array
          # - type: networking.gke.io/v1/serviceattachments
          #   updateSetting:
          #     includeDiff: true
          # - type: networking.gke.io/v1/servicenetworkendpointgroups
          #   updateSetting:
          #     includeDiff: true
          # - type: hub.gke.io/v1/memberships
          #   updateSetting:
          #     includeDiff: true
          - type: nodemanagement.gke.io/v1alpha1/updateinfos
            updateSetting:
              includeDiff: true
          ## calico
          - type: crd.projectcalico.org/v1/bgpconfigurations
            updateSetting:
              includeDiff: true
          - type: crd.projectcalico.org/v1/bgppeers
            updateSetting:
              includeDiff: true
          - type: crd.projectcalico.org/v1/blockaffinities
            updateSetting:
              includeDiff: true
          - type: crd.projectcalico.org/v1/clusterinformations
            updateSetting:
              includeDiff: true
          - type: crd.projectcalico.org/v1/felixconfigurations
            updateSetting:
              includeDiff: true
          - type: crd.projectcalico.org/v1/globalnetworkpolicies
            updateSetting:
              includeDiff: true
          - type: crd.projectcalico.org/v1/globalnetworksets
            updateSetting:
              includeDiff: true
          - type: crd.projectcalico.org/v1/hostendpoints
            updateSetting:
              includeDiff: true
          - type: crd.projectcalico.org/v1/ipamblocks
            updateSetting:
              includeDiff: true
          - type: crd.projectcalico.org/v1/ipamconfigs
            updateSetting:
              includeDiff: true
          - type: crd.projectcalico.org/v1/ipamhandles
            updateSetting:
              includeDiff: true
          - type: crd.projectcalico.org/v1/ippools
            updateSetting:
              includeDiff: true
          - type: crd.projectcalico.org/v1/networkpolicies
            updateSetting:
              includeDiff: true
          - type: crd.projectcalico.org/v1/networksets
            updateSetting:
              includeDiff: true
      context:
        rbac:
          group:
            prefix: ""
            static:
              values:
              - botkube-plugins-default
            type: Static
  security-kube-system:
    displayName: "kube-system security"
    botkube/kubernetes:
      enabled: true
      config:
        event:
          types:
          - create
          - update
          - delete
          - error
        namespaces:
          include:
            - kube-system
        resources:
          # K8s
          - type: v1/serviceaccounts
            event:   # WARN: too many `update` notifications
              types:
              - create
              - delete
              - error
            updateSetting:
              includeDiff: true
          - type: rbac.authorization.k8s.io/v1/clusterrolebindings
            updateSetting:
              includeDiff: true
              fields:
                - roleRef
                - subjects[*]
                # WARN: not always defined
                # - subjects[*].name
                # - subjects[*].namespace
          - type: rbac.authorization.k8s.io/v1/clusterroles
            updateSetting:
              includeDiff: true
              fields:
                - rules
          - type: rbac.authorization.k8s.io/v1/rolebindings
            updateSetting:
              includeDiff: true
              fields:
                - roleRef
                - subjects[*]
                # WARN: not always defined
                # - subjects[*].name
                # - subjects[*].namespace
          - type: rbac.authorization.k8s.io/v1/roles
            updateSetting:
              includeDiff: true
              fields:
                - rules
          - type: admissionregistration.k8s.io/v1/mutatingwebhookconfigurations
            updateSetting:
              includeDiff: true
          - type: admissionregistration.k8s.io/v1/validatingwebhookconfigurations
            updateSetting:
              includeDiff: true
          - type: networking.k8s.io/v1/ingresses
            updateSetting:
              includeDiff: true
              fields:
                - spec.rules   # array
          - type: networking.k8s.io/v1/networkpolicies
            updateSetting:
              includeDiff: true
              fields:
                - spec.podSelector
                - spec.policyTypes   # array
          # CRDs
          ## calico
          - type: crd.projectcalico.org/v1/bgpconfigurations
            updateSetting:
              includeDiff: true
          - type: crd.projectcalico.org/v1/bgppeers
            updateSetting:
              includeDiff: true
          - type: crd.projectcalico.org/v1/blockaffinities
            updateSetting:
              includeDiff: true
          - type: crd.projectcalico.org/v1/clusterinformations
            updateSetting:
              includeDiff: true
          - type: crd.projectcalico.org/v1/felixconfigurations
            updateSetting:
              includeDiff: true
          - type: crd.projectcalico.org/v1/globalnetworkpolicies
            updateSetting:
              includeDiff: true
          - type: crd.projectcalico.org/v1/globalnetworksets
            updateSetting:
              includeDiff: true
          - type: crd.projectcalico.org/v1/hostendpoints
            updateSetting:
              includeDiff: true
          - type: crd.projectcalico.org/v1/ipamblocks
            updateSetting:
              includeDiff: true
          - type: crd.projectcalico.org/v1/ipamconfigs
            updateSetting:
              includeDiff: true
          - type: crd.projectcalico.org/v1/ipamhandles
            updateSetting:
              includeDiff: true
          - type: crd.projectcalico.org/v1/ippools
            updateSetting:
              includeDiff: true
          - type: crd.projectcalico.org/v1/networkpolicies
            updateSetting:
              includeDiff: true
          - type: crd.projectcalico.org/v1/networksets
            updateSetting:
              includeDiff: true
      context:
        rbac:
          group:
            prefix: ""
            static:
              values:
              - botkube-plugins-default
            type: Static
  error:
    displayName: "Errors"
    botkube/kubernetes:
      enabled: true
      config:
        event:
          types:
          - error
        namespaces:
          include:
            - ".*"
          exclude:   # WARN: take precedence over `include`
            - kube-system
        resources:
          # K8s
          - type: v1/configmaps
          - type: v1/endpoints
          - type: v1/limitranges
          - type: v1/persistentvolumeclaims
          - type: v1/persistentvolumes
          # WARN: too many errors like "v1/pods error" (various reasons)
          # - type: v1/pods
          #   namespaces:
          #     include:
          #       - ".*"
          #     exclude:   # INFO: excluding namespaces in which cronjobs/jobs run, already covered by `*-jobs` sources
          #       - cicd-pipelines
          - type: v1/resourcequotas
          # - type: v1/secrets
          - type: v1/serviceaccounts
          - type: v1/services
          - type: apps/v1/daemonsets
          - type: apps/v1/deployments
          - type: apps/v1/statefulsets
          - type: batch/v1/cronjobs
          # - type: batch/v1/jobs
          - type: policy/v1/poddisruptionbudgets
          - type: apiextensions.k8s.io/v1/customresourcedefinitions
          - type: autoscaling/v1/horizontalpodautoscalers
          - type: rbac.authorization.k8s.io/v1/clusterrolebindings
          - type: rbac.authorization.k8s.io/v1/clusterroles
          - type: rbac.authorization.k8s.io/v1/rolebindings
          - type: rbac.authorization.k8s.io/v1/roles
          - type: admissionregistration.k8s.io/v1/mutatingwebhookconfigurations
          - type: admissionregistration.k8s.io/v1/validatingwebhookconfigurations
          - type: networking.k8s.io/v1/ingresses
          - type: networking.k8s.io/v1/networkpolicies
          - type: scheduling.k8s.io/v1/priorityclasses
          - type: storage.k8s.io/v1/storageclasses
          - type: snapshot.storage.k8s.io/v1/volumesnapshotclasses
          - type: snapshot.storage.k8s.io/v1/volumesnapshotcontents
          - type: snapshot.storage.k8s.io/v1/volumesnapshots
          # CRDs
          ## gcp/gke
          - type: cloud.google.com/v1/backendconfigs
          - type: cloud.google.com/v1beta1/backendconfigs
          # - type: networking.gke.io/v1/frontendconfigs
          - type: networking.gke.io/v1/managedcertificates
          # - type: networking.gke.io/v1/serviceattachments
          # - type: networking.gke.io/v1/servicenetworkendpointgroups
          # - type: hub.gke.io/v1/memberships
          - type: nodemanagement.gke.io/v1alpha1/updateinfos
          ## calico
          - type: crd.projectcalico.org/v1/bgpconfigurations
          - type: crd.projectcalico.org/v1/bgppeers
          - type: crd.projectcalico.org/v1/blockaffinities
          - type: crd.projectcalico.org/v1/clusterinformations
          - type: crd.projectcalico.org/v1/felixconfigurations
          - type: crd.projectcalico.org/v1/globalnetworkpolicies
          - type: crd.projectcalico.org/v1/globalnetworksets
          - type: crd.projectcalico.org/v1/hostendpoints
          - type: crd.projectcalico.org/v1/ipamblocks
          - type: crd.projectcalico.org/v1/ipamconfigs
          - type: crd.projectcalico.org/v1/ipamhandles
          - type: crd.projectcalico.org/v1/ippools
          - type: crd.projectcalico.org/v1/networkpolicies
          - type: crd.projectcalico.org/v1/networksets
          ## argocd
          - type: argoproj.io/v1alpha1/applications
            namespaces:
              exclude:
                - argocd
          - type: argoproj.io/v1alpha1/appprojects
          ## argo-events
          - type: argoproj.io/v1alpha1/eventbus
          - type: argoproj.io/v1alpha1/eventsources
          - type: argoproj.io/v1alpha1/sensors
          ## argo-workflows
          - type: argoproj.io/v1alpha1/clusterworkflowtemplates
          - type: argoproj.io/v1alpha1/workfloweventbindings
          - type: argoproj.io/v1alpha1/workflows
            namespaces:
              exclude:
                - cicd-pipelines   # WARN: too many notifications because of pipelines running
          - type: argoproj.io/v1alpha1/workflowtasksets
          - type: argoproj.io/v1alpha1/workflowtemplates
          ## monitoring - DEPRECATED: replace with VictoriaMetrics
          - type: monitoring.coreos.com/v1/alertmanagerconfigs
          - type: monitoring.coreos.com/v1/alertmanagers
          - type: monitoring.coreos.com/v1/podmonitors
          - type: monitoring.coreos.com/v1/probes
          - type: monitoring.coreos.com/v1/prometheuses
          - type: monitoring.coreos.com/v1/prometheusrules
          - type: monitoring.coreos.com/v1/servicemonitors
          - type: monitoring.coreos.com/v1/thanosrulers
          ## logging
          - type: logging.banzaicloud.io/v1beta1/clusterflows
          - type: logging.banzaicloud.io/v1beta1/clusteroutputs
          - type: logging.banzaicloud.io/v1beta1/flows
          - type: logging.banzaicloud.io/v1beta1/loggings
          - type: logging.banzaicloud.io/v1beta1/outputs
          - type: logging-extensions.banzaicloud.io/v1alpha1/eventtailers
          - type: logging-extensions.banzaicloud.io/v1alpha1/hosttailers
          ## treafik
          - type: traefik.containo.us/v1alpha1/ingressroutes
          - type: traefik.containo.us/v1alpha1/ingressroutetcps
          - type: traefik.containo.us/v1alpha1/ingressrouteudps
          - type: traefik.containo.us/v1alpha1/middlewares
          - type: traefik.containo.us/v1alpha1/middlewaretcps
          - type: traefik.containo.us/v1alpha1/serverstransports
          - type: traefik.containo.us/v1alpha1/tlsoptions
          - type: traefik.containo.us/v1alpha1/tlsstores
          - type: traefik.containo.us/v1alpha1/traefikservices
      context:
        rbac:
          group:
            prefix: ""
            static:
              values:
              - botkube-plugins-default
            type: Static
  error-kube-system:
    displayName: "kube-system errors"
    botkube/kubernetes:
      enabled: true
      config:
        event:
          types:
          - error
        namespaces:
          include:
            - kube-system
        resources:
          # K8s
          - type: v1/limitranges
          - type: v1/resourcequotas
          - type: v1/serviceaccounts
          - type: policy/v1/poddisruptionbudgets
          - type: apiextensions.k8s.io/v1/customresourcedefinitions
          - type: rbac.authorization.k8s.io/v1/clusterrolebindings
          - type: rbac.authorization.k8s.io/v1/clusterroles
          - type: rbac.authorization.k8s.io/v1/rolebindings
          - type: rbac.authorization.k8s.io/v1/roles
          - type: admissionregistration.k8s.io/v1/mutatingwebhookconfigurations
          - type: admissionregistration.k8s.io/v1/validatingwebhookconfigurations
          - type: networking.k8s.io/v1/ingresses
          - type: networking.k8s.io/v1/networkpolicies
          - type: scheduling.k8s.io/v1/priorityclasses
          # CRDs
          ## gcp/gke
          - type: cloud.google.com/v1/backendconfigs
          - type: cloud.google.com/v1beta1/backendconfigs
          # - type: networking.gke.io/v1/frontendconfigs
          - type: networking.gke.io/v1/managedcertificates
          # - type: networking.gke.io/v1/serviceattachments
          # - type: networking.gke.io/v1/servicenetworkendpointgroups
          # - type: hub.gke.io/v1/memberships
          - type: nodemanagement.gke.io/v1alpha1/updateinfos
          ## calico
          - type: crd.projectcalico.org/v1/bgpconfigurations
          - type: crd.projectcalico.org/v1/bgppeers
          - type: crd.projectcalico.org/v1/blockaffinities
          - type: crd.projectcalico.org/v1/clusterinformations
          - type: crd.projectcalico.org/v1/felixconfigurations
          - type: crd.projectcalico.org/v1/globalnetworkpolicies
          - type: crd.projectcalico.org/v1/globalnetworksets
          - type: crd.projectcalico.org/v1/hostendpoints
          - type: crd.projectcalico.org/v1/ipamblocks
          - type: crd.projectcalico.org/v1/ipamconfigs
          - type: crd.projectcalico.org/v1/ipamhandles
          - type: crd.projectcalico.org/v1/ippools
          - type: crd.projectcalico.org/v1/networkpolicies
          - type: crd.projectcalico.org/v1/networksets
      context:
        rbac:
          group:
            prefix: ""
            static:
              values:
              - botkube-plugins-default
            type: Static

configWatcher:
  enabled: true
  inCluster:
    informerResyncPeriod: 10m

plugins:
  cacheDir: /tmp
  repositories:
    botkube:
      url: https://github.com/kubeshop/botkube/releases/download/v1.8.0/plugins-index.yaml
  incomingWebhook:
    enabled: true
    # port and baseInClusterURL are set via envs
  restartPolicy:
    type: DeactivatePlugin
    threshold: 10
  healthCheckInterval: 10s

analytics:
  disable: false
```

</details>

## Slack threads

- https://botkube.slack.com/archives/C01CR1KS55K/p1709121554586339
- https://botkube.slack.com/archives/C01CR1KS55K/p1708685516373879

## Versions

Kubernetes: `v1.28.4-gke.1083000`
Platform: `GKE`
Botkube: `1.8.0`

### PR DESCRIPTION
**Pull request by pkosiec**
## Description

Changes proposed in this pull request:

- Reduce memory consumption for Kubernetes source configuration

This change groups Kubernetes source configurations by different kubeconfigs and creates a single `dynamicInformerFactory` per group, which essentially brings the implementation close to the 0.18 Kubernetes source one. 

## Stats

Memory consumption shortly after startup:

| Description | v1.9.1 | This PR |
|--------|--------|--------|
| No sources enabled | 21.4 MiB | 23.1 MiB |
| 1 source (`k8s-all-events2` from the PR instruction) | 78.9MiB | 86.6 MiB |
| 12 sources (from the PR instruction) | 504MB |  92.9 MiB |

### v1.9.1

12 sources:

#### 256Mi request, 384MB limit

Too low, source plugin restarts itself.

Screenshot 2024-04-02 at 19 11 11
Screenshot 2024-04-02 at 19 11 17

Screenshot 2024-04-02 at 19 11 04

#### 1Gi request + 2Gi request

Plugin runs withourt restarting, still multiple DeltaFIFO logs

image

image

image

#### 1 source (`k8s-all-events2` from the testing instruction)

image

#### No sources enabled

image

#### 12 Sources (from the testing instruction)

Requests 128Mi, limit 256Mi:

Screenshot 2024-04-03 at 10 43 05

Screenshot 2024-04-03 at 10 43 20

No DeltaFIFO logs, just a warning about client-side throttling:
```
{"level":"error","logger":"stderr","msg":"I0402 17:30:32.285424      13 request.go:697] Waited for 1.198321417s due to client-side throttling, not priority and fairness, request: GET:https://10.43.0.1:443/apis/networking.k8s.io/v1/ingresses?limit=500\u0026resourceVersion=0","plugin":"botkube/kubernetes","time":"2024-04-02T17:30:32Z"}
```
And Slack API rate limits:
```
{"level":"error","msg":"while sending bot message: 1 error occurred:\n\t* while sending Slack message to channel \"priv-channel\": while posting Slack message: slack rate limit exceeded, retry after 1s","time":"2024-04-03T07:51:21Z"}
{"level":"error","msg":"while sending bot message: 1 error occurred:\n\t* while sending Slack message to channel \"priv-channel\": while posting Slack message: slack rate limit exceeded, retry after 1s","time":"2024-04-03T07:51:21Z"}
```
#### 1 source (`k8s-all-events2` from the testing instruction)

Screenshot 2024-04-03 at 10 37 07

#### No sources enabled

image

## Testing

Check out this PR:
```
gh pr checkout 1425
```

Create k3d cluster

```
k3d cluster create
```

Build and serve plugins:
```
make build-plugins
PLUGIN_SERVER_HOST=http://host.k3d.internal go run ./hack/target/serve-plugins/main.go
```

Install kube-prometheus-stack:
```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm install prom prometheus-community/kube-prometheus-stack
```
Forward Grafana port:

```
kubectl port-forward svc/prom-grafana 3003:80
```

Navigate to http://localhost:3003 and log in with **admin** / **prom-operator** credentials.

Install ArgoCD + Flux on the cluster:
```
kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
kubectl apply -f https://github.com/fluxcd/flux2/releases/latest/download/install.yaml
```
### Install previous Botkube

Install previous Botkube version with the following configuration (fill the Slack tokens):

<details><summary>Details</summary>
<p>

```bash
cat <<EOF > /tmp/prev-values.yaml
settings:
  clusterName: "prev"

sources:
  'k8s-all-events2':
    displayName: "All events"
    botkube/kubernetes: &k8s-all-events
      context:
        rbac:
          group:
            type: Static
            prefix: ""
            static:
              values: [ "botkube-plugins-default" ]
      enabled: true
      config:
        namespaces:
          include:
            - ".*"
        event:
          types:
            - error
            - create
            - update
            - delete
        resources:
          - type: apiextensions.k8s.io/v1/customresourcedefinitions
          - type: argoproj.io/v1alpha1/applications
          - type: argoproj.io/v1alpha1/appprojects
          - type: notification.toolkit.fluxcd.io/v1beta1/alerts
          - type: source.toolkit.fluxcd.io/v1beta1/buckets
          - type: source.toolkit.fluxcd.io/v1beta1/gitrepositories
          - type: source.toolkit.fluxcd.io/v1beta1/helmcharts
          - type: helm.toolkit.fluxcd.io/v2beta1/helmreleases
          - type: source.toolkit.fluxcd.io/v1beta1/helmrepositories
          - type: image.toolkit.fluxcd.io/v1beta1/imagepolicies
          - type: image.toolkit.fluxcd.io/v1beta1/imagerepositories
          - type: image.toolkit.fluxcd.io/v1beta1/imageupdateautomations
          - type: kustomize.toolkit.fluxcd.io/v1beta1/kustomizations
          - type: source.toolkit.fluxcd.io/v1beta2/ocirepositories
          - type: notification.toolkit.fluxcd.io/v1beta1/providers
          - type: notification.toolkit.fluxcd.io/v1beta1/receivers
          - type: v1/services
          - type: networking.k8s.io/v1/ingresses
          - type: v1/nodes
            event:
              message:
                exclude:
                  - ".*nf_conntrack_buckets.*" # Ignore node related noisy messages from GKE clusters
          - type: v1/namespaces
          - type: v1/persistentvolumes
          - type: v1/persistentvolumeclaims
          - type: v1/configmaps
          - type: rbac.authorization.k8s.io/v1/roles
          - type: rbac.authorization.k8s.io/v1/rolebindings
          - type: rbac.authorization.k8s.io/v1/clusterrolebindings
          - type: rbac.authorization.k8s.io/v1/clusterroles
          - type: apps/v1/daemonsets
            event: # Overrides 'source'.kubernetes.event
              types:
                - create
                - update
                - delete
                - error
            updateSetting:
              includeDiff: true
              fields:
                - spec.template.spec.containers[*].image
                - status.numberReady
          - type: batch/v1/jobs
            event: # Overrides 'source'.kubernetes.event
              types:
                - create
                - update
                - delete
                - error
            updateSetting:
              includeDiff: true
              fields:
                - spec.template.spec.containers[*].image
                - status.conditions[*].type
          - type: apps/v1/deployments
            event: # Overrides 'source'.kubernetes.event
              types:
                - create
                - update
                - delete
                - error
            updateSetting:
              includeDiff: true
              fields:
                - spec.template.spec.containers[*].image
                - status.availableReplicas
          - type: apps/v1/statefulsets
            event: # Overrides 'source'.kubernetes.event
              types:
                - create
                - update
                - delete
                - error
            updateSetting:
              includeDiff: true
              fields:
                - spec.template.spec.containers[*].image
                - status.readyReplicas   
  'k8s-all-events3':
    displayName: "All events"
    botkube/kubernetes: *k8s-all-events
  'k8s-all-events4':
    displayName: "All events"
    botkube/kubernetes: *k8s-all-events      
  'k8s-all-events5':
    displayName: "All events"
    botkube/kubernetes: *k8s-all-events
  'k8s-all-events6':
    displayName: "All events"
    botkube/kubernetes: *k8s-all-events
  'k8s-all-events7':
    displayName: "All events"
    botkube/kubernetes: *k8s-all-events
  'k8s-all-events8':
    displayName: "All events"
    botkube/kubernetes: *k8s-all-events
  'k8s-all-events9':
    displayName: "All events"
    botkube/kubernetes: *k8s-all-events
  'k8s-all-events10':
    displayName: "All events"
    botkube/kubernetes: *k8s-all-events
  'k8s-all-events11':
    displayName: "All events"
    botkube/kubernetes: *k8s-all-events
  'k8s-all-events12':
    displayName: "All events"
    botkube/kubernetes: *k8s-all-events    
communications:
  'default-group':
    socketSlack:
      enabled: true
      appToken: "xapp-..."
      botToken: "xoxb-..."
      channels:
        'default':
          name: 'priv-channel'
          bindings:
            sources:
              - k8s-err-events
              - k8s-recommendation-events
              - k8s-err-with-logs-events
              - k8s-create-events
              - k8s-all-events
              - k8s-all-events2
              - k8s-all-events3
              - k8s-all-events4
              - k8s-all-events5
              - k8s-all-events6
              - k8s-all-events7
              - k8s-all-events8
              - k8s-all-events9
              - k8s-all-events10
              - k8s-all-events11
              - k8s-all-events12              
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi
EOF

botkube install --version v1.9.1 -f /tmp/prev-values.yaml
```

</p>
</details> 

In the Grafana dashboard, navigate to the `1. Kubernetes / Compute Resources / Pod` dashboard and select the Botkube pod. Observe the memory consumption.

### Install current Botkube

Install current Botkube version with the following configuration (fill the Slack tokens):

<details><summary>Details</summary>
<p>

```bash
cat <<EOF > /tmp/new-values.yaml 
image:
  repository: kubeshop/pr/botkube
  tag: 1425-PR

settings:
  clusterName: "new"

plugins:
  repositories:
    botkube:
       url: http://host.k3d.internal:3010/botkube.yaml

sources:
  'k8s-all-events2':
    displayName: "All events"
    botkube/kubernetes: &k8s-all-events
      context:
        rbac:
          group:
            type: Static
            prefix: ""
            static:
              values: [ "botkube-plugins-default" ]
      enabled: true
      config:
        namespaces:
          include:
            - ".*"
        event:
          types:
            - error
            - create
            - update
            - delete
        resources:
          - type: apiextensions.k8s.io/v1/customresourcedefinitions
          - type: argoproj.io/v1alpha1/applications
          - type: argoproj.io/v1alpha1/appprojects
          - type: notification.toolkit.fluxcd.io/v1beta1/alerts
          - type: source.toolkit.fluxcd.io/v1beta1/buckets
          - type: source.toolkit.fluxcd.io/v1beta1/gitrepositories
          - type: source.toolkit.fluxcd.io/v1beta1/helmcharts
          - type: helm.toolkit.fluxcd.io/v2beta1/helmreleases
          - type: source.toolkit.fluxcd.io/v1beta1/helmrepositories
          - type: image.toolkit.fluxcd.io/v1beta1/imagepolicies
          - type: image.toolkit.fluxcd.io/v1beta1/imagerepositories
          - type: image.toolkit.fluxcd.io/v1beta1/imageupdateautomations
          - type: kustomize.toolkit.fluxcd.io/v1beta1/kustomizations
          - type: source.toolkit.fluxcd.io/v1beta2/ocirepositories
          - type: notification.toolkit.fluxcd.io/v1beta1/providers
          - type: notification.toolkit.fluxcd.io/v1beta1/receivers
          - type: v1/services
          - type: networking.k8s.io/v1/ingresses
          - type: v1/nodes
            event:
              message:
                exclude:
                  - ".*nf_conntrack_buckets.*" # Ignore node related noisy messages from GKE clusters
          - type: v1/namespaces
          - type: v1/persistentvolumes
          - type: v1/persistentvolumeclaims
          - type: v1/configmaps
          - type: rbac.authorization.k8s.io/v1/roles
          - type: rbac.authorization.k8s.io/v1/rolebindings
          - type: rbac.authorization.k8s.io/v1/clusterrolebindings
          - type: rbac.authorization.k8s.io/v1/clusterroles
          - type: apps/v1/daemonsets
            event: # Overrides 'source'.kubernetes.event
              types:
                - create
                - update
                - delete
                - error
            updateSetting:
              includeDiff: true
              fields:
                - spec.template.spec.containers[*].image
                - status.numberReady
          - type: batch/v1/jobs
            event: # Overrides 'source'.kubernetes.event
              types:
                - create
                - update
                - delete
                - error
            updateSetting:
              includeDiff: true
              fields:
                - spec.template.spec.containers[*].image
                - status.conditions[*].type
          - type: apps/v1/deployments
            event: # Overrides 'source'.kubernetes.event
              types:
                - create
                - update
                - delete
                - error
            updateSetting:
              includeDiff: true
              fields:
                - spec.template.spec.containers[*].image
                - status.availableReplicas
          - type: apps/v1/statefulsets
            event: # Overrides 'source'.kubernetes.event
              types:
                - create
                - update
                - delete
                - error
            updateSetting:
              includeDiff: true
              fields:
                - spec.template.spec.containers[*].image
                - status.readyReplicas   
  'k8s-all-events3':
    displayName: "All events"
    botkube/kubernetes: *k8s-all-events
  'k8s-all-events4':
    displayName: "All events"
    botkube/kubernetes: *k8s-all-events      
  'k8s-all-events5':
    displayName: "All events"
    botkube/kubernetes: *k8s-all-events
  'k8s-all-events6':
    displayName: "All events"
    botkube/kubernetes: *k8s-all-events
  'k8s-all-events7':
    displayName: "All events"
    botkube/kubernetes: *k8s-all-events
  'k8s-all-events8':
    displayName: "All events"
    botkube/kubernetes: *k8s-all-events
  'k8s-all-events9':
    displayName: "All events"
    botkube/kubernetes: *k8s-all-events
  'k8s-all-events10':
    displayName: "All events"
    botkube/kubernetes: *k8s-all-events
  'k8s-all-events11':
    displayName: "All events"
    botkube/kubernetes: *k8s-all-events
  'k8s-all-events12':
    displayName: "All events"
    botkube/kubernetes: *k8s-all-events    
communications:
  'default-group':
    socketSlack:
      enabled: true
      appToken: "xapp-..."
      botToken: "xoxb-..."
      channels:
        'default':
          name: 'priv-channel'
          bindings:
            sources:
              - k8s-err-events
              - k8s-recommendation-events
              - k8s-err-with-logs-events
              - k8s-create-events
              - k8s-all-events
              - k8s-all-events2
              - k8s-all-events3
              - k8s-all-events4
              - k8s-all-events5
              - k8s-all-events6
              - k8s-all-events7
              - k8s-all-events8
              - k8s-all-events9
              - k8s-all-events10
              - k8s-all-events11
              - k8s-all-events12                
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
EOF

botkube install --version v1.9.1 -f /tmp/new-values.yaml
```

</p>
</details> 

In the Grafana dashboard, navigate to the `1. Kubernetes / Compute Resources / Pod` dashboard and select the Botkube pod. Observe the memory consumption.

## Related issue(s)

Resolves #1403

### CODE REVIEW

File: internal/source/kubernetes/source.go [hunk 1]
```diff
@@ -163,17 +224,13 @@ func consumeEvents(ctx context.Context, s Source) {
 		func(resource string) (cache.SharedIndexInformer, error) {
 			gvr, err := parseResourceArg(resource, client.mapper)
 			if err != nil {
-				s.logger.Infof("Unable to parse resource: %s to register with informer\n", resource)
+				globalLogger.Infof("Unable to parse resource: %s to register with informer\n", resource)
```
Comment (mszostok) [inline internal/source/kubernetes/source.go:227]:
```suggestion
				globalLogger.WithError(err).Errorf("Unable to parse resource: %s to register with informer\n", resource)
```

File: internal/source/kubernetes/source.go [hunk 2]
```diff
@@ -85,54 +118,82 @@ func (*Source) Stream(ctx context.Context, input source.StreamInput) (source.Str
...
-		clusterName:              input.Context.ClusterName,
-		kubeConfig:               input.Context.KubeConfig,
-		isInteractivitySupported: input.Context.IsInteractivitySupported,
+	globalSrcCfg, err := s.getGlobalSrcCfg()
+	if err != nil {
+		exitOnError(err, loggerx.New(pkgConfig.Logger{}).WithField("error", err.Error()))
+	}
+
+	id := s.configStore.Len()
+	globalLogger := loggerx.NewStderr(pkgConfig.Logger{
```
Comment (mszostok) [inline internal/source/kubernetes/source.go:138]: if that's the "global" one (maybe better `system/internal` (?)) shouldn't we just assign it to `s` instead of passing it as arg? Of course, assign it after `s.bgProcessor.StopAndWait` when we know that all previous configured services are cleaned up.

File: internal/source/kubernetes/source.go [hunk 3]
```diff
@@ -184,78 +241,119 @@ func consumeEvents(ctx context.Context, s Source) {
...
+			if !ok {
+				errs = multierror.Append(errs, fmt.Errorf("source with key %q not found", sourceKey))
+			}
 
-	if recommendation.ShouldIgnoreEvent(&recCfg, e) {
-		s.logger.Debugf("Skipping event as it is related to recommendation informers and doesn't have any recommendations: %#v", e)
-		return
-	}
+			if srcCfg.ActiveSourceConfig == nil {
+				globalLogger.Errorf("ActiveSourceConfig not found for source %s", srcCfg.name)
```
Comment (mszostok) [inline internal/source/kubernetes/source.go:291]: if error should we then add it to `errs`? from what I see, it should never happen, right? so if it happens, then there is a bug?

File: internal/source/kubernetes/source.go [hunk 4]
```diff
@@ -184,78 +241,119 @@ func consumeEvents(ctx context.Context, s Source) {
...
+
+			// Filter events
+			e = srcCfg.filterEngine.Run(ctx, eventCopy)
+			if e.Skip {
+				srcCfg.logger.Debugf("Skipping event: %#v", eventCopy)
+				continue
+			}
+
+			if len(e.Kind) <= 0 {
+				srcCfg.logger.Warn("sendEvent received e with Kind nil. Hence skipping.")
```
Comment (mszostok) [inline internal/source/kubernetes/source.go:305]: let's improve that log msg 😄

File: internal/source/kubernetes/source.go [hunk 5]
```diff
@@ -184,78 +241,119 @@ func consumeEvents(ctx context.Context, s Source) {
...
+			}
+
+			if recommendation.ShouldIgnoreEvent(&recCfg, eventCopy) {
+				srcCfg.logger.Debugf("Skipping event as it is related to recommendation informers and doesn't have any recommendations: %#v", e)
+				continue
+			}
+
+			msg, err := srcCfg.messageBuilder.FromEvent(eventCopy, srcCfg.cfg.ExtraButtons)
+			if err != nil {
+				srcCfg.logger.Errorf("while rendering message from event: %w", err)
```
Comment (mszostok) [inline internal/source/kubernetes/source.go:323]: why here we just log it and not append to `errs`? on the other hand,  in line 312 we append it to `errs` but we don't log it. Please pick unified approach.

File: internal/source/kubernetes/source.go [hunk 6]
```diff
@@ -184,78 +241,119 @@ func consumeEvents(ctx context.Context, s Source) {
...
+				RawObject:       eventCopy,
+				AnalyticsLabels: event.AnonymizedEventDetailsFrom(eventCopy),
+			}
+
+			srcCfg.eventCh <- message
+		}
+
+		if errs.ErrorOrNil() != nil {
+			globalLogger.Errorf("while sending event: %w", errs)
+		}
```
Comment (mszostok) [inline internal/source/kubernetes/source.go:338]:
```suggestion
		if err := errs.ErrorOrNil(); err != nil {
			globalLogger.WithError(err).Errorf("Failed to send %s event", e.Name)
		}
```

**Review by mszostok — COMMENTED** [review]
Just the code comments. I will approve it once I will execute it on my end 👍

File: internal/source/kubernetes/configuration_store.go [hunk 7]
```diff
@@ -0,0 +1,91 @@
...
+	val, ok := c.store[sourceKey]
+	return val, ok
+}
+
+// GetGlobal returns global SourceConfig.
+func (c *configurationStore) GetGlobal() (SourceConfig, bool) {
+	c.lock.RLock()
+	defer c.lock.RUnlock()
+
+	sortedKeys := c.sortedKeys()
```
[the remark this answers is not in the document]
Comment (pkosiec) [reply internal/source/kubernetes/configuration_store.go:55]: yeah, right, it's a leftover from my prev attempt of this implementation 👍

File: internal/source/kubernetes/source.go [hunk 8]
```diff
@@ -85,54 +118,82 @@ func (*Source) Stream(ctx context.Context, input source.StreamInput) (source.Str
...
-		eventCh:                  make(chan source.Event),
-		config:                   cfg,
-		logger:                   log,
-		clusterName:              input.Context.ClusterName,
-		kubeConfig:               input.Context.KubeConfig,
-		isInteractivitySupported: input.Context.IsInteractivitySupported,
+	globalSrcCfg, err := s.getGlobalSrcCfg()
+	if err != nil {
+		exitOnError(err, loggerx.New(pkgConfig.Logger{}).WithField("error", err.Error()))
+	}
```
[the remark this answers is not in the document]
Comment (pkosiec) [reply internal/source/kubernetes/source.go:135]: Agree, it's not needed anymore, this is a leftover after my refactor 👍

File: internal/source/kubernetes/source.go (hunk 3 above)
Comment (pkosiec) [reply internal/source/kubernetes/source.go:291]: yes, it shouldn't happen. Agree, should be added to errs.
I've replaced the line with

```go
errs = multierror.Append(errs, fmt.Errorf("ActiveSourceConfig not found for source %s. This seems to be a bug", srcCfg.name))
```

**Review by mszostok — APPROVED** [review]
tested e2e 👍 LGTM
Screenshot 2024-04-03 at 14 52 34

File: internal/source/kubernetes/source.go (hunk 2 above)
Comment (pkosiec) [reply internal/source/kubernetes/source.go:138]: Agree, I've renamed the logger to `system` one 👍 

Yes, as we have mutex on `Stream`, we could assign the logger to `s`.
However, I'd like to keep passing every non-thread-safe argument to the `configureProcessForSources` as value, to avoid unexpected behavior in future if someone modifies the method. Hope that's OK for you 👍

File: internal/source/kubernetes/source.go [hunk 9]
```diff
@@ -184,78 +241,119 @@ func consumeEvents(ctx context.Context, s Source) {
...
-		Message:         msg,
-		RawObject:       e,
-		AnalyticsLabels: event.AnonymizedEventDetailsFrom(e),
+func (s *Source) genFnForKubeconfig(id int, kubeConfig []byte, globalLogger logrus.FieldLogger, informerResyncPeriod time.Duration, srcCfgs map[string]SourceConfig) func(ctx context.Context) {
+	return func(ctx context.Context) {
+		err := s.configureProcessForSources(ctx, id, kubeConfig, globalLogger, informerResyncPeriod, srcCfgs)
+		if err != nil {
+			exitOnError(fmt.Errorf("while configuring process for sources: %w", err), globalLogger.WithFields(logrus.Fields{
+				"srcEvent": config.ErrorEvent,
+				"dstEvent": config.WarningEvent,
```
[the remark this answers is not in the document]
Comment (pkosiec) [reply internal/source/kubernetes/source.go:348]: Right 😄 this is wrong
