### PR TITLE
Fix kubectl builder perms checker

### LINKED ISSUE #1379: Handle non-native k8s verbs in `kubectl` auth service
## Description

In interactive `kubectl` builder, we return **"You don't have enough permissions"** for `describe`, `top`, `api-resources` even though the assigned RBAC allows doing it.

## Expected behavior

The `kubectl` builder respect assigned plugin RBAC.

### PR DESCRIPTION
**Pull request by mszostok**
## Description

Changes proposed in this pull request:

- Fix kubectl builder perms checker

## Testing

Demo recording uploaded to Slack as it doesn't fit GitHub limits: https://kubeshop.slack.com/archives/C03MRCX7UE9/p1707757327981479?thread_ts=1707493295.011349&cid=C03MRCX7UE9

Screenshot 2024-02-12 at 18 07 25
Screenshot 2024-02-12 at 18 07 39
Screenshot 2024-02-12 at 18 08 26

Here is the config that I used for testing:

<details><summary>YAML Config</summary>
<p>

```yaml
communications:
  default-group:
    socketSlack:
      enabled: true
      channels:
        default:
          name: no-rbac
          bindings:
            sources: []
            executors: 
              - kc-missing-rbac
        reader:
          name: reader
          bindings:
            executors:
              - kc-reader
        deleter:
          name: deleter
          bindings:
            executors:
              - kc-deleter
      appToken: "xapp-1-"
      botToken: "xoxb-"

executors:
  kc-missing-rbac:
    botkube/kubectl:
      enabled: true
      context:
        rbac:
          group:
            type: Static
            static:
              values: [ "not-found" ]
      config:
        defaultNamespace: "default"
        interactiveBuilder:
          allowed:
            verbs: [ "api-resources", "api-versions", "cluster-info", "describe", "explain", "get", "logs", "top", "delete" ]
            resources: [ "deployments", "pods", "namespaces", "daemonsets", "statefulsets", "storageclasses", "nodes", "configmaps", "services", "ingresses", "replicasets", "secrets", "cronjobs", "jobs" ]

  kc-reader:
    botkube/kubectl:
      enabled: true
      context:
        rbac:
          group:
            type: Static
            static:
              values: [ "botkube-plugins-default" ]
      config:
        defaultNamespace: "default"
        interactiveBuilder:
          allowed:
            verbs: [ "api-resources", "api-versions", "cluster-info", "describe", "explain", "get", "logs", "top", "delete" ]
            resources: [ "deployments", "pods", "namespaces", "daemonsets", "statefulsets", "storageclasses", "nodes", "configmaps", "services", "ingresses", "replicasets", "secrets", "cronjobs", "jobs" ]

  kc-deleter:
    botkube/kubectl:
      enabled: true
      context:
        rbac:
          group:
            type: Static
            static:
              values: [ "flux-write" ]
      config:
        defaultNamespace: "default"
        interactiveBuilder:
          allowed:
            verbs: [ "api-resources", "api-versions", "cluster-info", "describe", "explain", "get", "logs", "top", "delete" ]
            resources: [ "deployments", "pods", "namespaces", "daemonsets", "statefulsets", "storageclasses", "nodes", "configmaps", "services", "ingresses", "replicasets", "secrets", "cronjobs", "jobs" ]

plugins:
  cacheDir: "/tmp/plugins"
  repositories:
    botkube:
      url: http://host.k3d.internal:3010/botkube.yaml

settings:
  log:
    level: "debug"
    formatter: text
  kubeconfig: "/Users/mszostok/.kube/config"
  clusterName: "labs"
  upgradeNotifier: false

analytics:
  disable: true

```

</p>
</details> 

## Related issue(s)

Fix #1379

### CODE REVIEW

**Comment by mszostok** [comment]
CI tests are failing in the same way on `main` so it's not related to do PR itself: https://github.com/kubeshop/botkube/actions/runs/7870841341/job/21473234766

We need to investigate that.

File: test/helpers/plugin_server.go [hunk 1]
```diff
@@ -26,7 +26,7 @@ func main() {
 	portInt, err := strconv.Atoi(port)
 	loggerx.ExitOnError(err, "while starting server")
 
-	binDir := filepath.Join(dir, "plugin-dist")
+	binDir := filepath.Join(dir, "../plugin-dist")
```
Comment (pkosiec) [inline test/helpers/plugin_server.go:29]: What is the reason if this change?

**Review by pkosiec — APPROVED** [review]
Code and demo LGTM 🚀 didn't test it personally, but I'll try it out after releasing the latest main plugins 👍

File: test/helpers/plugin_server.go (hunk 1 above)
Comment (mszostok) [reply test/helpers/plugin_server.go:29]: tests no have own `go.mod` you need to run server from `tests` folder and it breaks the flow as the `dir` is taken from the current path 🙂
