### PR TITLE
Fix help flag error, remove color codes

### LINKED ISSUE #1229: Flux plugin doesn't return help message
## Expected behavior

When running `@Botkube flux delete source git --help` we get:
```
while parsing args: pflag: help requested
```

## AC

- add support for returning help messages
- remove color tags from output string, right now we have:
    ```
    while running command: [?25l[2K
    [1m[34m?[0m [1mAre you sure you want to delete this source git[0m? [2m[y/N][0m █
    [1A[2K
    [2K
    [?25h
    ✗ aborting
    
    exit status 1
    ```

### PR DESCRIPTION
**Pull request by mszostok**
## Description

Changes proposed in this pull request:

- Fix help flag error, remove color codes

## Testing

1. `env PLUGIN_SERVER_HOST=http://host.k3d.internal go run test/helpers/plugin_server.go`
2. `PLUGIN_TARGETS="flux" make build-plugins-single`
3. Botkube config:
    ```yaml
    communications:
      default-group:
        socketSlack:
          enabled: true
          channels:
            default:
              name: hakuna-matata
              bindings:
                sources: []
                executors:
                  - flux
          appToken: "xapp-1-"
          botToken: "xoxb-"
    
    
    executors:
      flux:
        botkube/flux:
          enabled: true
          config:
            log:
              level: "debug"
    
          context:
            rbac:
              group:
                type: Static
                static:
                  values: [ "system:masters" ]
    
    plugins:
      cacheDir: "/tmp/plugins"
    
      repositories:
        botkube:
          url: http://host.k3d.internal:3010/botkube.yaml
    
    settings:
      log:
        level: "debug"
        formatter: "text"
      clusterName: "labs"
      upgradeNotifier: false
    
    analytics:
      disable: true
    
    configWatcher:
      enabled: false
    ```
4. Commands to run:
    ```
    @Botkube flux delete source git --help
    ```
    ```
    @Botkube flux create source git webapp-latest
       --url=https://github.com/stefanprodan/podinfo 
       --branch=master 
       --interval=3m
    ```
    ```
    @Botkube flux delete source git webapp-latest
    ```
    ```
    @Botkube flux delete source git webapp-latest -s
    ```

Screenshot 2023-09-07 at 10 13 15

## Related issue(s)

Fix #1229

### CODE REVIEW

File: internal/executor/flux/commands.go [hunk 1]
```diff
@@ -35,9 +39,19 @@ func normalize(in string) string {
...
 	if err != nil {
 		return "", err
 	}
-	return color.ClearCode(out.CombinedOutput()), nil
+	return out.CombinedOutput(), nil
+}
+
+// isConfirmDelete uses string contains in order to detect if a user was asked to confirm deletion.
+// For now, there is no better way as we use terminal output not Go SDK.
+func isConfirmDelete(err error) bool {
```
Comment (pkosiec) [inline internal/executor/flux/commands.go:52]: WDYT about:
```suggestion
// isDeleteConfirmationErr uses string contains in order to detect if a user was asked to confirm deletion.
// For now, there is no better way as we use terminal output not Go SDK.
func isDeleteConfirmationErr(err error) bool {
```

**Review by pkosiec — APPROVED** [review]
Works well 👌
